#!/bin/bash

# Get the C file name from the environment variable
CFILE=$CFILE

# Generate the output file name with .s extension
OUTPUT_FILE="${CFILE%.*}.s"

# Run the C file through the compiler to generate assembly code
gcc -S -masm=intel "$CFILE" -o "$OUTPUT_FILE"
